import { sprite, type Sprite } from './sprite.ts'

// Small item sprites: treats, room gifts, adventure souvenirs and UI icons.

export const TREAT_ART: Record<string, Sprite> = {
  strawberry: sprite([
    '....o..o....',
    '...oGooGo...',
    '..oGgGGgGo..',
    '.orrGggGrro.',
    'orwrrGGrrrro',
    'orrrryrrryro',
    'oryrrrrrrrRo',
    '.orrrryrrRo.',
    '.orryrrrrRo.',
    '..orrrrRRo..',
    '...oRRRRo...',
    '....oooo....',
  ]),
  onigiri: sprite([
    '.....oo.....',
    '....occo....',
    '...occwco...',
    '...occcco...',
    '..occcccco..',
    '..oceccеco..'.replace('е', 'e'),
    '.ocpccccpco.',
    '.occxxxxcco.',
    'occxxxxxxcco',
    'occxxxxxxcco',
    'osscxxxxcsso',
    '.oooooooooo.',
  ]),
  dango: sprite([
    '....oooo....',
    '...oPwPPo...',
    '...oPPPmo...',
    '...oooooo...',
    '...ocwcco...',
    '...occcso...',
    '...oooooo...',
    '...ogwggo...',
    '...oggGGo...',
    '....oooo....',
    '.....hn.....',
    '.....hn.....',
  ]),
  cookie: sprite([
    '....oooo....',
    '..ootttto...',
    '.otttNtttoo.',
    '.otNtttttto.',
    'otttttttNtho',
    'otttNtttttho',
    'otttttNtttho',
    'otNttttttthо'.replace('о', 'o'),
    '.otttttNtho.',
    '.ohtttttthо.'.replace('о', 'o'),
    '..oohhhhoo..',
    '....oooo....',
  ]),
  cupcake: sprite([
    '.....oo.....',
    '....orRo....',
    '..oooooooo..',
    '.oPPiPPPPPo.',
    'oPPPPPPiPPPo',
    'omPPPPPPPPmo',
    'ommmmmmmmmmo',
    '.oohnhnhnoo.',
    '.ohnhnhnhno.',
    '.ohnhnhnhno.',
    '..ohnhnhno..',
    '..oooooooo..',
  ]),
  cocoa: sprite([
    '..w...w.....',
    '...w...w....',
    '..w...w.....',
    '.oooooooo...',
    'ocwcnnncwo..',
    'oPPPPPPPPooo',
    'oPPPPPPPPo.o',
    'oPPmPPPPPo.o',
    'oPmmmPPPPooo',
    'oPPmPPPPPo..',
    '.oPPPPPPo...',
    '..oooooo....',
  ]),
  taiyaki: sprite([
    '............',
    '..oooooo..oo',
    '.oyyyyyyooyo',
    'oyeyyYyyYyyo',
    'oyyyyyyyyyo.',
    'oyyyYyyYyyo.',
    'oYyyyyyyyyyo',
    '.oYyyYyyYoYo',
    '..oYYYYYooYo',
    '...oooooo.oo',
    '............',
    '............',
  ]),
  peach: sprite([
    '......o.oo..',
    '.....onoGGo.',
    '...ooonogo..',
    '..oPPPoaaoo.',
    '.oPiPPoaaaao',
    'oPPPPaaaaaAo',
    'oPPPaaaaaaAo',
    'oaPaaaaaaaAo',
    'oaaaaaaaaAAo',
    '.oaaaaaaAAo.',
    '..oAaaAAAo..',
    '...oooooo...',
  ]),
}

export const GIFT_ART: Record<string, Sprite> = {
  plant: sprite([
    '.....oo..oo.....',
    '....ogGooggo....',
    '..oogggGoggGoo..',
    '.ogggGggoggggGo.',
    'ogGgggoggGgoggGo',
    'oggGogggGggGgggo',
    '.oggggGoggoGggo.',
    'ogGgoggggggggGgo',
    'oggggGgGoggGgggo',
    '.oggGggggGgggoo.',
    '..ooggGoGggooo..',
    '....oooGoooo....',
    '...oAAAAAAAAo...',
    '...oaaaaaaaao...',
    '...oAAAAAAAAo...',
    '....oaaaaaao....',
    '....oaaaaaAo....',
    '....oaaaaaAo....',
    '.....oooooo.....',
  ]),
  books: sprite([
    '...ooooooo..',
    '...oUUUUUco.',
    '...oUyUUUco.',
    '.ooooooooooo',
    '.orrrrrrrcco',
    '.orrryrrrcco',
    'oooooooooooo',
    'ogggggggccco',
    'ogggyggggcco',
    'oooooooooooo',
  ]),
  mushroomLamp: sprite([
    '...oooo...',
    '..orrwro..',
    '.orwrrrwro',
    'orrrrwrrro',
    'oRRRRRRRRo',
    '.oooooooo.',
    '...ocso...',
    '...ocso...',
    '...ocso...',
    '.oonnnnoo.',
    '.oooooooo.',
  ]),
  cactus: sprite([
    '...ooo...',
    '...omo...',
    '..ooooo..',
    '.ogGgGgo.',
    'ogGgwgGgo',
    'ogGgGgGgo',
    'ogGwGgGgo',
    '.ogGgGgo.',
    '.oaaaaao.',
    '.oAaaaAo.',
    '..ooooo..',
  ]),
  yarn: sprite([
    '...oooo...',
    '..omPmmo..',
    '.omPmmPmo.',
    'ommmPmmPmo',
    'oPmmmPmmmo',
    'omPmmmPmmo',
    '.ommPmmmo.',
    '..oPmmPo.o',
    '...oooo.o.',
  ]),
  teddy: sprite(
    [
      '.oo...',
      'ohno..',
      'ohhooo',
      '.ohhhh',
      'ohhehh',
      'ohhhtt',
      'ophhte',
      '.ohhhh',
      '.oommm',
      'ohhhhh',
      'ohhhtt',
      'ohnhtt',
      '.ooooo',
    ].map((r) => r + [...r].reverse().join('')),
  ),
  painting: sprite([
    'oooooooooooooooo',
    'oYYYYYYYYYYYYYYo',
    'oYooooooooooooYo',
    'oYouuuuuuuyyuoYo',
    'oYouuwwuuuyyuoYo',
    'oYouuuuuuuuuuoYo',
    'oYouuuuuugguuoYo',
    'oYougguuggGguoYo',
    'oYoggGggggggGoYo',
    'oYoGgggGgggggoYo',
    'oYooooooooooooYo',
    'oYYYYYYYYYYYYYYo',
    'oooooooooooooooo',
  ]),
  snowGlobe: sprite([
    '..ooooo..',
    '.oqqwqqo.',
    'oqwqqqqqo',
    'oqqqgqqwo',
    'oqqgggqqo',
    'oqwqNqqqo',
    '.occccco.',
    '..ooooo..',
    '.oRRRRRo.',
    '.oRyRyRo.',
    '.ooooooo.',
  ]),
  cushion: sprite([
    '..oooooooooooooo..',
    '.oyyyyyyyyyyyyyyo.',
    'oyywyyyyYyyyyyyyyo',
    'oyyyyyyyyyyyyYyyyo',
    'oYyyyyYyyyyyyyyyYo',
    '.oYYYYYYYYYYYYYYo.',
    '..oooooooooooooo..',
  ]),
  heartRug: sprite([
    '...oooooooooo...',
    '.ooPPPPPPPPPPoo.',
    'oPPPPmmPPmmPPPPo',
    'oPPPmmmmmmmmPPPo',
    'oPPPPmmmmmmPPPPo',
    '.ooPPPPmmPPPPoo.',
    '...oooooooooo...',
  ]),
  fairyLights: sprite([
    'o..........o',
    '.oo......oo.',
    '.y.oooooo.m.',
    '.Y..u..y..R.',
    '....U..Y....',
  ]),
}

export const SOUVENIR_ART: Record<string, Sprite> = {
  mapleLeaf: sprite([
    '.....oo.....',
    '....oAAo....',
    '.o..oAAo..o.',
    'oAoooArooaAo',
    'oAAAAArAAAAo',
    '.oAAaArAaAo.',
    '..oAAArAAo..',
    '.oAAAArAAAo.',
    'oAAooArAoAAo',
    'ooo.oNNo.ooo',
    '.....oNo....',
    '......oo....',
  ]),
  berries: sprite([
    '......ooo...',
    '....ooGgo...',
    '...oGggo....',
    '..oGoGo.....',
    '.ooUoooUo...',
    'oUwUUoUwUo..',
    'oUUUxooUUxo.',
    '.oUxoUUoxo..',
    '..ooUwUUo...',
    '...oUUUxo...',
    '....oxxo....',
    '.....oo.....',
  ]),
  lilyPad: sprite([
    '....oo.oo...',
    '...omPomPo..',
    '...oPmPmPo..',
    '.oooomPmoooo',
    'oggggooogggo',
    'ogGggggggGgo',
    'oggGgggggggo',
    'ogggggGgggGo',
    '.oGgggggGgo.',
    '..ooooooooo.',
  ]),
  star: sprite([
    '.....oo.....',
    '....oyyo....',
    '....oyyo....',
    'ooooyyyyoooo',
    'oyyyyyyyyyYo',
    '.oyyeyyeyYo.',
    '..oypyypyo..',
    '..oyyyyyYo..',
    '.oyyYooYyYo.',
    '.oyYo..oYYo.',
    'oYYo....oYYo',
    'ooo......ooo',
  ]),
  shell: sprite([
    '....oooo....',
    '..ooPiPPoo..',
    '.oPiPmPiPmo.',
    'oPPiPmPiPmPo',
    'oPmiPmPiPmPo',
    'oPmiPmPiPmPo',
    '.oPiPmPiPmo.',
    '..oPiPmPio..',
    '...ooPPoo...',
    '...oPPPPo...',
    '....oooo....',
  ]),
  mushroom: sprite([
    '...oooooo...',
    '.oorrwwrroo.',
    'orrrrwwrrrro',
    'orwwrrrrwwro',
    'orwwrrrrrrRo',
    'oRRRRRRRRRRo',
    '.oooccccooo.',
    '...occsco...',
    '...occcso...',
    '...occcso...',
    '....oooo....',
  ]),
  bookmark: sprite([
    '...oooooo...',
    '...occcco...',
    '...ocmmco...',
    '...omymmo...',
    '...ocmmco...',
    '...ocGcco...',
    '...occGco...',
    '...ocGcco...',
    '...occcco...',
    '...ocoocо...'.replace('о', 'o'),
    '...oo..oo...',
  ]),
  feather: sprite([
    '.........oo.',
    '.......oowo.',
    '......owwwo.',
    '.....owzwo..',
    '....owwzo...',
    '...owzwwo...',
    '...owwzo....',
    '..owzwo.....',
    '..owwo......',
    '.ooo........',
    'oo..........',
    'o...........',
  ]),
  pinecone: sprite([
    '.....oo.....',
    '....onno....',
    '...onhnno...',
    '..onhnhnno..',
    '..ohnhnhno..',
    '.onhnhnhnno.',
    '.ohnhnhnhno.',
    '..onhnhnno..',
    '..ohnhnhno..',
    '...onhnno...',
    '....onno....',
    '.....oo.....',
  ]),
}

export const ICON_ART: Record<string, Sprite> = {
  heart: sprite([
    '............',
    '..oo....oo..',
    '.orro..orro.',
    'orwrroorrrro',
    'orwrrrrrrrro',
    'orrrrrrrrrRo',
    'orrrrrrrrrRo',
    '.orrrrrrrRo.',
    '..orrrrrRo..',
    '...orrrRo...',
    '....orRo....',
    '.....oo.....',
  ]),
  acorn: sprite([
    '.....oo.....',
    '.....on.....',
    '..oooooooo..',
    '.onhnhnhnho.',
    'onhnhnhnhnho',
    'oNNNNNNNNNNo',
    '.oYyyYYYYYo.',
    '.oYyYYYYYYo.',
    '.oYYYYYYYAo.',
    '..oYYYYYAo..',
    '...oYYAAo...',
    '....oooo....',
  ]),
  flame: sprite([
    '.....o......',
    '....oAo.....',
    '....oAAo....',
    '...oAAAo.o..',
    '..oAAyAAoAo.',
    '..oAyyyAAAo.',
    '.oAAyyyyAAo.',
    '.oAyywyyyAo.',
    '.oAyyyyyyAo.',
    '..oAyyyyAo..',
    '...oAAAAo...',
    '....oooo....',
  ]),
  mail: sprite([
    '............',
    '............',
    'oooooooooooo',
    'ooiiiiiiiioo',
    'oioiiiiiioio',
    'oiioiiiioiio',
    'oiiiommoiiio',
    'oiiiimmiiiio',
    'oiiiiiiiiiio',
    'oooooooooooo',
    '............',
    '............',
  ]),
  chart: sprite([
    '............',
    '........ooo.',
    '........ogo.',
    '....ooo.ogo.',
    '....omo.ogo.',
    '....omo.ogo.',
    'ooo.omo.ogo.',
    'oyo.omo.ogo.',
    'oyo.omo.ogo.',
    'oyo.omo.ogo.',
    'oooooooooooo',
    '............',
  ]),
  gear: sprite([
    '.....oo.....',
    '..o.ovvo.o..',
    '.ovoovvoovo.',
    '..ovvvvvvo..',
    '.oovvoovvoo.',
    'ovvvo..ovvvo',
    'ovvvo..ovvvo',
    '.oovvoovvoo.',
    '..ovvvvvvo..',
    '.ovoovvoovo.',
    '..o.ovvo.o..',
    '.....oo.....',
  ]),
  backpack: sprite([
    '....oooo....',
    '...oo..oo...',
    '..oooooooo..',
    '.ogggggggGo.',
    '.ogggggggGo.',
    '.oooooooooo.',
    '.ogoooooogo.',
    '.ogoyyyyogo.',
    '.ogooooooGo.',
    '.ogggggggGo.',
    '..oooooooo..',
    '............',
  ]),
  gift: sprite([
    '..oo....oo..',
    '.omPo..oPmo.',
    '..ommoommo..',
    'oooooooooooo',
    'ouuuummuuuuo',
    'oUUUUmmUUUUo',
    'oooooooooooo',
    '.ouuummuuuo.',
    '.ouuummuuuo.',
    '.ouuummuuuo.',
    '.oUUUmmUUUo.',
    '.oooooooooo.',
  ]),
  bow: sprite([
    '.oo.....oo.',
    'oPmo...oPmo',
    'oPmmoooPmmo',
    'ommmoPommmo',
    'ommmoooommo',
    '.ooomo.ooo.',
    '...omo.omo.',
    '...oo...oo.',
  ]),
}

/** Furniture that's always in the room (the fox uses these on its own). */
export const ROOM_ART: Record<string, Sprite> = {
  desk: sprite([
    '.oooooooooooooooooooooooooooooooooooooo.',
    'ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhho',
    'onnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnno',
    '.oooooooooooooooooooooooooooooooooooooo.',
    '..onno.......................ohhhhhhho..',
    '..onno.......................ohhhYhhho..',
    '..onno.......................ooooooooo..',
    '..onno.......................ohhhhhhho..',
    '..onno.......................ohhhYhhho..',
    '..onno.......................ooooooooo..',
    '..onno.......................onno.onno..',
    '..onno.......................onno.onno..',
    '..oooo.......................oooo.oooo..',
  ]),
  lamp: sprite([
    '.ooooooooo.',
    'oGGGGGGGGGo',
    'oGgGGGGGGGo',
    'ooooooooooo',
    '.oyyyyyyyo.',
    '.....oYo...',
    '.....oYo...',
    '.....oYo...',
    '...ooYYYoo.',
    '..oYYYYYYYo',
    '..ooooooooo',
  ]),
  casebooks: sprite([
    'oooo.........',
    'oRro.........',
    'oRrooooo.....',
    'oYyoUuuo.....',
    'oRroYyyoooooo',
    'oRroUuuoGggGo',
    'oYyoUuuoYyyYo',
    'oRroYyyoGggGo',
    'oRroUuuoGggGo',
    'ooooooooooooo',
  ]),
  bowlEmpty: sprite([
    '............',
    '............',
    '..oooooooo..',
    '.oNNNNNNNNo.',
    'oooooooooooo',
    'ommmmmmmmmmo',
    '.oPPPPPPPPo.',
    '..oooooooo..',
  ]),
  bowlFull: sprite([
    '....oooo....',
    '..oohnhnoo..',
    '.onhnhnhnho.',
    '.ohnhnhnhno.',
    'oooooooooooo',
    'ommmmmmmmmmo',
    '.oPPPPPPPPo.',
    '..oooooooo..',
  ]),
  tub: sprite(
    [
      '.oooooooooooooo',
      'owwwwwwwwwwwwww',
      'oqqqqqqqqqqqqqq',
      '.oPPPPPPPPPPPPP',
      '.oPiPPPPPPPPPPP',
      '.oPiPPPPPPPPPPP',
      '.oPPPPPPPPPPPPP',
      '..oPPPPPPPPPPPP',
      '..omPPPPPPPPPPP',
      '...ommmmmmmmmmm',
      '....ooooooooooo',
      '....oYo........',
      '...oYYo........',
      '...ooo.........',
    ].map((r) => r + [...r].reverse().join('')),
  ),
  ball: sprite(['..ooo..', '.orrwo.', 'orrrwro', 'owwwwwo', 'ouuwggo', '.ouwgo.', '..ooo..']),
}

/** Law decor, unlocked by the fox's career. */
export const LAW_ART: Record<string, Sprite> = {
  diploma: sprite([
    'ooooooooooooooo',
    'onnnnnnnnnnnnno',
    'onooooooooooono',
    'onocccccccccono',
    'onocZZZZZZZcono',
    'onocccccccccono',
    'onocZZZZZcccono',
    'onoccccccRRcono',
    'onocccccRrRcono',
    'onooooooooooono',
    'onnnnnnnnnnnnno',
    'ooooooooooooooo',
  ]),
  gavel: sprite([
    '.oooo.......',
    'onnhno......',
    'onnhnoooooo.',
    'onnhnhhhhhho',
    'onnhnoooooo.',
    'onnhno......',
    '.oooo.......',
  ]),
  scales: sprite([
    '......o......',
    '.....oyo.....',
    'oYYYYYyYYYYYo',
    '.o....Y....o.',
    'o.o...Y...o.o',
    'o.o...Y...o.o',
    'yyyy..Y..yyyy',
    '.YY...Y...YY.',
    '.....oYo.....',
    '...oYYYYYo...',
    '...ooooooo...',
  ]),
}

export const NEED_ICON_ART: Record<string, Sprite> = {
  moon: sprite([
    '....oooo....',
    '..ooyyyyo...',
    '.oyyyyoo....',
    '.oyyyo......',
    'oyyyo.......',
    'oyyyo.......',
    'oyyyo.......',
    'oyyyyo......',
    '.oyyyyoo..o.',
    '.oyyyyyyooyo',
    '..ooyyyyyyo.',
    '....oooooo..',
  ]),
  bubbles: sprite([
    '.......ooo..',
    '......owqqo.',
    '......oqqqo.',
    '..oooo.ooo..',
    '.owwqqo.....',
    'owqqqqqo....',
    'oqqqqqqo.oo.',
    'oqqqqqqooqqo',
    '.oqqqqo.oqqo',
    '..oooo...oo.',
    '............',
    '............',
  ]),
  ball: sprite([
    '....oooo....',
    '..oorrwwoo..',
    '.orrrrwwyyo.',
    '.orrrrwwyyo.',
    'orrrrrwwyyyo',
    'owwwwwwwwwwo',
    'owwwwwwwwwwo',
    'ouuuuwwgggGo',
    '.ouuuwwgggo.',
    '.ouuuwwggGo.',
    '..oouwwgoo..',
    '....oooo....',
  ]),
  card: sprite([
    '............',
    '..oooooooooo',
    '..owwwwwwwwo',
    'oooooooooowo',
    'owwwwwwwwowo',
    'owZZZZZZwowo',
    'owwwwwwwwowo',
    'owZZZZwwwoo.',
    'owwwwwwmwo..',
    'oooooooooo..',
    '............',
    '............',
  ]),
  gavel: sprite([
    '............',
    '..oooo......',
    '.onnnnooooo.',
    '.onhhnhhhhho',
    '.onnnnooooo.',
    '..oooo......',
    '............',
    '..oooooooo..',
    '.onnnnnnnno.',
    '.ohhhhhhhho.',
    '..oooooooo..',
    '............',
  ]),
  palette: sprite([
    '...oooooo...',
    '.oottttttoo.',
    'ottrrtttuuto',
    'otrrtttttuuo',
    'ottttoottttо'.replace('о', 'o'),
    'otyyto.otggo',
    'otyytoootggo',
    'otttttttttto',
    '.ootmmttttoo',
    '...oommtoo..',
    '.....oooo...',
    '............',
  ]),
}

export const SPECIAL_ART: Record<string, Sprite> = {
  cake: sprite([
    '...y..y..y...',
    '...Y..Y..Y...',
    '...u..m..u...',
    '...u..m..u...',
    '.ooooooooooo.',
    'oiiPiiiPiiiPo',
    'oPiPPiPPiPPio',
    'ohhhhhhhhhhho',
    'orrrrrrrrrrro',
    'ohhhhhhhhhhho',
    'ooooooooooooo',
    '.ozzzzzzzzzo.',
  ]),
  jackOLantern: sprite([
    '....oo....',
    '...oGo....',
    '.oooooooo.',
    'oAaAaaAaAo',
    'oaNNaaNNao',
    'oAaNaaNaAo',
    'oaNaNNaNao',
    'oAaNNNNaAo',
    '.oooooooo.',
  ]),
  openBook: sprite([
    '.ooooo.ooooo.',
    'occccooccccco',
    'oczzzcoczzzco',
    'occccooccccco',
    'oczzccoczzcco',
    'ooooooooooooo',
  ]),
}

export const BRUSH_ART = sprite(['.oooooooo.', 'oPPPPPPPPo', 'ommmmmmmmo', '.oooooooo.', '.t.t.t.t..'])
